// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// landscape_gauss
List landscape_gauss(NumericMatrix coord, NumericMatrix SignalOut, NumericMatrix signalExp, NumericMatrix signalCtrl, int resolutionValue, double zoomValue, double increase, double sigma, double occFrac, NumericVector weights);
RcppExport SEXP _levi_landscape_gauss(SEXP coordSEXP, SEXP SignalOutSEXP, SEXP signalExpSEXP, SEXP signalCtrlSEXP, SEXP resolutionValueSEXP, SEXP zoomValueSEXP, SEXP increaseSEXP, SEXP sigmaSEXP, SEXP occFracSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type coord(coordSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type SignalOut(SignalOutSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type signalExp(signalExpSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type signalCtrl(signalCtrlSEXP);
    Rcpp::traits::input_parameter< int >::type resolutionValue(resolutionValueSEXP);
    Rcpp::traits::input_parameter< double >::type zoomValue(zoomValueSEXP);
    Rcpp::traits::input_parameter< double >::type increase(increaseSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type occFrac(occFracSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(landscape_gauss(coord, SignalOut, signalExp, signalCtrl, resolutionValue, zoomValue, increase, sigma, occFrac, weights));
    return rcpp_result_gen;
END_RCPP
}
// nearest_node_grid
IntegerMatrix nearest_node_grid(NumericMatrix coordNodes, int resolutionValue, double zoomValue, double increase);
RcppExport SEXP _levi_nearest_node_grid(SEXP coordNodesSEXP, SEXP resolutionValueSEXP, SEXP zoomValueSEXP, SEXP increaseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type coordNodes(coordNodesSEXP);
    Rcpp::traits::input_parameter< int >::type resolutionValue(resolutionValueSEXP);
    Rcpp::traits::input_parameter< double >::type zoomValue(zoomValueSEXP);
    Rcpp::traits::input_parameter< double >::type increase(increaseSEXP);
    rcpp_result_gen = Rcpp::wrap(nearest_node_grid(coordNodes, resolutionValue, zoomValue, increase));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_levi_landscape_gauss", (DL_FUNC) &_levi_landscape_gauss, 10},
    {"_levi_nearest_node_grid", (DL_FUNC) &_levi_nearest_node_grid, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_levi(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
