# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Landscape by normalised convolution with a Gaussian kernel
#'
#' @param coord n x 2 matrix with the normalised coordinates of the points
#'   (nodes followed by edge midpoints).
#' @param SignalOut n x 1 matrix with the combined signal (test vs control).
#' @param signalExp n x 1 matrix with the test signal.
#' @param signalCtrl n x 1 matrix with the control signal.
#' @param resolutionValue side of the square output grid.
#' @param zoomValue coordinate of the lower-left corner of the grid.
#' @param increase grid step, in coordinate units.
#' @param sigma kernel width, in grid cells.
#' @param occFrac fraction of the occupancy produced by an isolated point
#'   below which the cell is considered background and gets NA.
#' @param weights optional n-vector of non-negative support weights, one per
#'   point. A point of weight w counts as w copies of itself in both the
#'   numerator and the occupancy; weight 0 removes it. Empty means all ones.
#' @return List with m1 (combined signal), m2 (test), m3 (control) and occ
#'   (relative network occupancy), all of them resolutionValue x
#'   resolutionValue matrices.
#' @keywords internal
landscape_gauss <- function(coord, SignalOut, signalExp, signalCtrl, resolutionValue, zoomValue, increase, sigma, occFrac, weights = numeric(0)) {
    .Call('_levi_landscape_gauss', PACKAGE = 'levi', coord, SignalOut, signalExp, signalCtrl, resolutionValue, zoomValue, increase, sigma, occFrac, weights)
}

#' Index of the node nearest to each grid cell
#'
#' Used by the GUI to report which gene a region selected on the landscape
#' belongs to. Brute force in O(res^2 * n), exact and cheap: for a network of
#' 1200 nodes on a 240 x 240 grid this is about 70 million comparisons.
#'
#' @param coordNodes n x 2 matrix with the normalised coordinates of the nodes.
#' @param resolutionValue side of the square grid.
#' @param zoomValue coordinate of the lower-left corner of the grid.
#' @param increase grid step.
#' @return Integer matrix resolutionValue x resolutionValue with the
#'   (1-based) index of the node nearest to each cell.
#' @keywords internal
nearest_node_grid <- function(coordNodes, resolutionValue, zoomValue, increase) {
    .Call('_levi_nearest_node_grid', PACKAGE = 'levi', coordNodes, resolutionValue, zoomValue, increase)
}

