# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SigCoordPiso <- function(coord, resolutionValue, gamaValue, increase, contrastValue, zoomValue, numberCoord) {
    .Call('_levi_SigCoordPiso', PACKAGE = 'levi', coord, resolutionValue, gamaValue, increase, contrastValue, zoomValue, numberCoord)
}

matrix_entrada <- function(coordPiso, SignalOut, signalExp, signalCtrl, coord, resolutionValue, increase, zoomValue, numberCoord) {
    .Call('_levi_matrix_entrada', PACKAGE = 'levi', coordPiso, SignalOut, signalExp, signalCtrl, coord, resolutionValue, increase, zoomValue, numberCoord)
}

matrix_saida <- function(matrixIn, resolutionValue, smoothValue, gamaValue, increase, zoomValue, h) {
    .Call('_levi_matrix_saida', PACKAGE = 'levi', matrixIn, resolutionValue, smoothValue, gamaValue, increase, zoomValue, h)
}

